### PR TITLE
Fix: double-prefix when using permalink()

### PR DESCRIPTION
**Pull request by jfowl**
As mentioned here: https://github.com/Elderjs/elderjs/pull/128/files#r571693545

### CODE REVIEW

**Comment by schnubor** [comment]
I think you just need to remove deprecated tests as well and this can be merged.

**Comment by kiuKisas** [comment]
Is it ready to merge ?

**Comment by kiuKisas** [comment]
Sorry for the wait, I'll be busy with some works. I should be more active now :)
I tried and it seems to work as expected.
Regarding test,  we don't need to specify "without prefix"  in the remaining test "work without prefix", it can be confusing. Can you please rename it ? I'll merge after that :)

**Comment by jfowl** [comment]
> Sorry for the wait, I'll be busy with some works. I should be more active now :)
> I tried and it seems to work as expected.
> Regarding test, we don't need to specify "without prefix" in the remaining test "work without prefix", it can be confusing. Can you please rename it ? I'll merge after that :)

Sorry, I don't really understand what you want there: The "works without prefix" test case checks that without specifying a prefix, the permalinks don't add that prefix.
Which other name do you propose, because I currently can't think of a more fitting one.

**Comment by kiuKisas** [comment]
because prefix is out of the permalink scope now, it "works with or without prefix", except if I miss something ? 
so it does make

**Comment by kiuKisas** [comment]
Sorry, misclick the "close with comment" button

**Pull request merged**
