### PR TITLE
v1.5 feature: Esbuild for Dev Mode

### PR DESCRIPTION
**Pull request by nickreese**
Major undertaking to make the rollup plugin generic so that esbuild can be used in dev mode.

Took our dev builds down from 11s to 1.1s. 

## How to Test It

Clone the template project

```
npx degit Elderjs/template elderjs-app
cd elderjs-app
```

Then

`npm i --save @elderjs/elderjs@next`

Create `esbuild.js` in the root of your project.

```js
// ./esbuild.js
const { esbuildBundler } = require('@elderjs/elderjs');

esbuildBundler();
```

to run: 

`node esbuild`

This has a major drop in test coverage which I'd prefer to avoid but due to the refactor all of the rollup plugin tests break.

### CODE REVIEW

**Comment by Xuffasch** [comment]
Hello,

I've tested the new build process with a new project and I got this error : 

<pre>
Error: Build failed with 1 error:
/Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/fs-extra/lib/output/index.js:31:14: error: [plugin: esbuild-plugin-elderjs] The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of SourceMapGenerator
    at failureErrorWithLog (/Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/esbuild/lib/main.js:1466:15)
    at /Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/esbuild/lib/main.js:1148:28
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  errors: [
    {
      pluginName: 'esbuild-plugin-elderjs',
      text: 'The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of SourceMapGenerator',
      location: {
        file: '/Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/fs-extra/lib/output/index.js',
        namespace: 'file',
        line: 31,
        column: 14,
        length: 0,
        lineText: '    return fs.writeFileSync(file, ...args)\n' +
          '    at Object.writeFileSync (node:fs:1505:5)\n' +
          '    at Object.outputFileSync (/Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/fs-extra/lib/output/index.js:31:15)\n' +
          '    at /Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/@elderjs/elderjs/build/esbuild/esbuildPluginSvelte.js:128:40\n' +
          '    at processTicksAndRejections (node:internal/process/task_queues:93:5)',
        suggestion: ''
      },
      notes: [
        {
          text: 'This error came from the "onEnd" callback registered here',
          location: {
            file: '/Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/@elderjs/elderjs/build/esbuild/esbuildPluginSvelte.js',
            namespace: 'file',
            line: 116,
            column: 18,
            length: 5,
            lineText: '            build.onEnd(async () => {\n' +
              '    at setup (/Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/@elderjs/elderjs/build/esbuild/esbuildPluginSvelte.js:116:19)\n' +
              '    at /Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/esbuild/lib/main.js:756:23\n' +
              '    at Generator.next (<anonymous>)\n' +
              '    at /Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/esbuild/lib/main.js:42:61\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at __async (/Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/esbuild/lib/main.js:26:10)\n' +
              '    at handlePlugins (/Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/esbuild/lib/main.js:729:69)\n' +
              '    at Object.buildOrServe (/Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/esbuild/lib/main.js:1041:7)\n' +
              '    at /Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/esbuild/lib/main.js:1765:17',
            suggestion: ''
          }
        }
      ],
      detail: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of SourceMapGenerator
          at Object.writeFileSync (node:fs:1505:5)
          at Object.outputFileSync (/Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/fs-extra/lib/output/index.js:31:15)
          at /Users/tristanlucas/LocalData/Svelte/elderjs/ship-node/node_modules/@elderjs/elderjs/build/esbuild/esbuildPluginSvelte.js:128:40
          at processTicksAndRejections (node:internal/process/task_queues:93:5) {
        code: 'ERR_INVALID_ARG_TYPE'
      }
    }
  ],
</pre>

I hope this helps.

**Comment by nickreese** [comment]
@Xuffasch thanks for this. Will push an update today. The sourcemap isn’t getting stringified on the fs call.

**Comment by nickreese** [comment]
@Xuffasch Tagged a new release. Try `npm i --save @elderjs/elderjs@next` and rerun. 👍

**Comment by Xuffasch** [comment]
@nickreese Yes It worked for me !

**Comment by jerriclynsjohn** [comment]
Some of the errors that I'm getting on an otherwise error free repo
1. `error: Could not resolve "@newwwton/components" (mark it as external to exclude it from the bundle)`
2. `error: [plugin: esbuild-plugin-elderjs] ENOENT: no such file or directory, open 'XXXXXX\src\components\atoms\TextInput\intl-tel-input\build\css\intlTelInput.css'`

```bash
note: This error came from the "onLoad" callback registered here
     99 │                 build.onLoad({ filter: /\.css$/ }, async ({ path }) => {
```

**Pull request merged**
