### PR TITLE
fix build error on windows

### LINKED ISSUE #102: Build error with v1.2.1: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
Hello!

First of all, thank you so much for Elder.js! Really love working with it!!
Since I was excited about the new release, I decided to try it out. But I am getting an error during build:
`TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined`

Seems to be coming from the dynamic require of ssr (in src/utils/svelteComponent.ts):
```
// eslint-disable-next-line import/no-dynamic-require
const ssrReq = require(ssr);
```

Not sure if this is caused by something on my local machine or not. Any ideas what I can do to fix this?

(The error also occurs with a clean install of latest Elderjs/template btw...)

### PR DESCRIPTION
**Pull request by kfrederix**
Fixes #102

### CODE REVIEW

**Comment by kfrederix** [comment]
It seems to break the tests somehow, sorry. I 'll try fix that...

**Comment by nickreese** [comment]
@kfrederix I think glob expects linux style paths. This has tripped me up before. Are the globs returning empty?

I really need a windows dev env.

**Comment by nickreese** [comment]
I’m mobile but if the tests are using path.resolve on the mock’d glob that would cause inconsistency with how glob works. Could be a bug in the test.

**Comment by kfrederix** [comment]
@nickreese yeah I think you are right. I am currently out of time to spend on this unfortunately. I 'll check back when I have more time in the upcoming days...

**Comment by kfrederix** [comment]
@nickreese tests are passing now on windows as well. I made a few more changes to `prepareFindSvelteComponent ` to make it more robust...

**Comment by nickreese** [comment]
@kfrederix 👏 Awesome. Looks good. Thank you.

**Comment by x4080** [comment]
Hi @kfrederix , I tried the latest (v1.2.4) and still wont run in windows

```
> Elder.js running on http://localhost:3000
/ [
  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
      at validateString (internal/validators.js:124:11)
      at Module.require (internal/modules/cjs/loader.js:945:3)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.templateComponent (D:\svelteprojects\elderjs-app\node_modules\@elderjs\elderjs\build\utils\svelteComponent.js:20:20)
      at buildPage (D:\svelteprojects\elderjs-app\node_modules\@elderjs\elderjs\build\utils\Page.js:43:40)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Object.run (D:\svelteprojects\elderjs-app\node_modules\@elderjs\elderjs\build\hooks\index.js:81:34)
      at async D:\svelteprojects\elderjs-app\node_modules\@elderjs\elderjs\build\utils\prepareRunHook.js:46:44
      at async processHook (D:\svelteprojects\elderjs-app\node_modules\@elderjs\elderjs\build\utils\prepareRunHook.js:41:13)
      at async Array.prepServer (D:\svelteprojects\elderjs-app\node_modules\@elderjs\elderjs\build\utils\prepareServer.js:8:9) {
    code: 'ERR_INVALID_ARG_TYPE'
  }
]
```

Did it work in your side ?

**Comment by kfrederix** [comment]
@x4080 yes it works for me with latest version. But please note: in the elderjs template the version the version is still locked to 1.2.1 (from package-lock.json). Can you try running `npm i @elderjs/elderjs` (this will upgrade to latest elderjs version v1.2.4) and then try to build/run it...?

**Comment by x4080** [comment]
@kfrederix Oh I didnt know that, I'll try it thanks for the tip

**Comment by x4080** [comment]
It works nicely, 
```
npm i @elderjs/elderjs
```
is the key, if I try manually change the package.json to 1.2.4, still wont work

**Comment by nickreese** [comment]
@x4080 @kfrederix Removed the package lock and updated the package on the template. Thanks. 👍

**Comment by x4080** [comment]
@nickreese Thanks and happy new year !

**Pull request merged**
